# .github/release.yml

changelog:
  exclude:
    authors:
      - dependabot
  categories:
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Bug Fixes 🐛
      labels:
        - bug
    - title: Documentation 📚
      labels:
        - docs
    - title: Dependencies 📦
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - '*'
