name: 📝 Basic Issue
description: File a basic issue.
type: Task
projects: ['intility/56']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!
  - type: textarea
    attributes:
      label: What's the issue?
      description: Please describe the issue.
      placeholder: I have an issue...
    validations:
      required: true
