// AUTO-GENERATED by `dotnet jsonapi-typegen`. Do not edit by hand.

export interface Article {
  id: string;
  title: string;
  body: string | null;
  published: boolean;
  publishedAt: string | null;
  viewCount: number;
  tags: string[];
  authorId: number;
  author: Author | null;
  comments: Comment[];
}

export interface Author {
  id: string;
  name: string;
  email: string | null;
}

export interface Comment {
  id: string;
  text: string;
  createdAt: string;
  articleId: number;
  authorId: number;
  article: Article | null;
  author: Author | null;
}

export const ResourceMap = {
  Article: { type: "articles", relationships: ["author", "comments"] },
  Author: { type: "authors", relationships: [] },
  Comment: { type: "comments", relationships: ["article", "author"] },
} as const;
