// AUTO-GENERATED by `dotnet jsonapi-typegen`. Do not edit by hand.
import type { JsonApiResourceDescriptor } from "../../clients/typescript/src/index.ts";

export interface Article {
  id: string;
  title: string;
  body: string | null;
  published: boolean;
  publishedAt: string | null;
  viewCount: number;
  tags: string[];
  authorId: number;
  author: Author | null;
  comments: Comment[];
}

export const Article: JsonApiResourceDescriptor<Article> = {
  type: "articles",
  attributes: ["title", "body", "published", "publishedAt", "viewCount", "tags", "authorId"],
  toOne: ["author"],
  toMany: ["comments"],
};

export interface Author {
  id: string;
  name: string;
  email: string | null;
}

export const Author: JsonApiResourceDescriptor<Author> = {
  type: "authors",
  attributes: ["name", "email"],
  toOne: [],
  toMany: [],
};

export interface Comment {
  id: string;
  text: string;
  createdAt: string;
  articleId: number;
  authorId: number;
  article: Article | null;
  author: Author | null;
}

export const Comment: JsonApiResourceDescriptor<Comment> = {
  type: "comments",
  attributes: ["text", "createdAt", "articleId", "authorId"],
  toOne: ["article", "author"],
  toMany: [],
};
