<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- Package metadata -->
    <PackageId>Intility.JsonApiToolkit</PackageId>
    <Version>1.6.0</Version>
    <Authors>Intility</Authors>
    <Company>Intility</Company>
    <Description>A toolkit for implementing JSON:API specification in .NET applications</Description>
    <PackageTags>jsonapi;api;rest;dotnet</PackageTags>
    <RepositoryUrl>https://github.com/intility/Intility.JsonApiToolkit</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <!-- Generate XML documentation -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="JsonApiToolkit.Tests"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="9.0.2"/>
    <PackageReference Include="Intility.Logging.AspNetCore" Version="3.0.3"/>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.0"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.2"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2"/>
  </ItemGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>
</Project>
