<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- Package metadata -->
    <PackageId>Intility.JsonApiToolkit</PackageId>
    <Version>2.1.2</Version>
    <Authors>Intility</Authors>
    <Company>Intility</Company>
    <Description>A toolkit for implementing JSON:API specification in .NET applications</Description>
    <PackageTags>jsonapi;api;rest;dotnet</PackageTags>
    <RepositoryUrl>https://github.com/intility/json-api-toolkit</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>

    <!-- Generate XML documentation -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="JsonApiToolkit.Tests"/>
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    <PackageReference Include="Intility.Logging.AspNetCore" Version="3.1.4"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.7"/>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>
</Project>
