using System.Reflection;
using System.Text;
using JsonApiToolkit.Extensions.Querying;
using JsonApiToolkit.Mapping;

namespace JsonApiToolkit.TypeGen;

/// <summary>
/// Turns [JsonApiResource]-attributed CLR types into TypeScript. Reuses
/// EntityMapper's attribute/relationship split so the generated types
/// describe exactly what the toolkit puts on the wire.
/// </summary>
public static class TypeScriptEmitter
{
    public static string Generate(IReadOnlyList<(Type Type, string WireType)> resources)
    {
        var wireTypeByType = resources.ToDictionary(r => r.Type, r => r.WireType);
        var ordered = resources.OrderBy(r => r.Type.Name, StringComparer.Ordinal).ToList();
        var nullability = new NullabilityInfoContext();

        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED by `dotnet jsonapi-typegen`. Do not edit by hand.");
        sb.AppendLine();

        foreach ((Type? type, string _) in ordered)
        {
            EmitInterface(sb, type, wireTypeByType, nullability);
            sb.AppendLine();
        }

        EmitResourceMap(sb, ordered, wireTypeByType);
        return sb.ToString();
    }

    private static void EmitInterface(
        StringBuilder sb,
        Type type,
        Dictionary<Type, string> wireTypeByType,
        NullabilityInfoContext nullability
    )
    {
        sb.AppendLine($"export interface {type.Name} {{");
        sb.AppendLine("  id: string;"); // JSON:API ids are always strings on the wire

        foreach (PropertyInfo prop in EntityMapper.GetAttributeProperties(type))
        {
            (string TsType, bool Nullable)? mapped = MapAttributeType(prop, nullability);
            if (mapped is null)
            {
                Console.Error.WriteLine(
                    $"warning: {type.Name}.{prop.Name} has an unsupported type "
                        + $"({prop.PropertyType}), skipped. Extend MapScalar to include it."
                );
                continue;
            }

            (string? tsType, bool nullable) = mapped.Value;
            sb.AppendLine(
                $"  {EntityMapper.GetAttributeName(prop)}: {tsType}{(nullable ? " | null" : "")};"
            );
        }

        foreach (PropertyInfo prop in EntityMapper.GetRelationshipProperties(type))
        {
            bool isCollection = TypeHelpers.IsCollectionType(prop.PropertyType);
            Type targetType = TypeHelpers.GetNavigationTargetType(prop.PropertyType);

            if (!wireTypeByType.ContainsKey(targetType))
            {
                Console.Error.WriteLine(
                    $"warning: {type.Name}.{prop.Name} relates to {targetType.Name}, which "
                        + "has no [JsonApiResource]. Add the attribute to include this relationship."
                );
                continue;
            }

            // Honest hydration types: an un-included relationship is null/[],
            // not "whatever the C# nullability annotation says".
            string tsType = isCollection ? $"{targetType.Name}[]" : $"{targetType.Name} | null";
            sb.AppendLine($"  {EntityMapper.GetAttributeName(prop)}: {tsType};");
        }

        sb.AppendLine("}");
    }

    private static void EmitResourceMap(
        StringBuilder sb,
        List<(Type Type, string WireType)> ordered,
        Dictionary<Type, string> wireTypeByType
    )
    {
        sb.AppendLine("export const ResourceMap = {");
        foreach ((Type? type, string? wireType) in ordered)
        {
            IEnumerable<string> relationships = EntityMapper
                .GetRelationshipProperties(type)
                .Where(p =>
                    wireTypeByType.ContainsKey(TypeHelpers.GetNavigationTargetType(p.PropertyType))
                )
                .Select(p => $"\"{EntityMapper.GetAttributeName(p)}\"");

            sb.AppendLine(
                $"  {type.Name}: {{ type: \"{wireType}\", relationships: [{string.Join(", ", relationships)}] }},"
            );
        }
        sb.AppendLine("} as const;");
    }

    /// <summary>
    /// Maps a scalar attribute property to a TS type. Returns null for types
    /// the tool does not understand yet (caller warns and skips).
    /// </summary>
    private static (string TsType, bool Nullable)? MapAttributeType(
        PropertyInfo prop,
        NullabilityInfoContext nullability
    )
    {
        Type? underlying = Nullable.GetUnderlyingType(prop.PropertyType);
        bool nullableValueType = underlying != null;
        Type effective = underlying ?? prop.PropertyType;

        if (TypeHelpers.IsCollectionType(effective))
        {
            Type? elementType = TypeHelpers.GetCollectionElementType(effective);
            string? elementTs = elementType is null ? null : MapScalar(elementType);
            return elementTs is null ? null : ($"{elementTs}[]", false);
        }

        bool nullableRefType =
            !effective.IsValueType
            && nullability.Create(prop).ReadState == NullabilityState.Nullable;

        string? ts = MapScalar(effective);
        return ts is null ? null : (ts, nullableValueType || nullableRefType);
    }

    private static string? MapScalar(Type type)
    {
        if (type == typeof(string) || type == typeof(Guid))
            return "string";
        if (type == typeof(bool))
            return "boolean";
        if (type == typeof(DateTime) || type == typeof(DateTimeOffset))
            return "string";
        if (IsNumeric(type))
            return "number";
        if (type.IsEnum)
            return string.Join(" | ", Enum.GetNames(type).Select(n => $"\"{n}\""));

        return null;
    }

    private static bool IsNumeric(Type t) =>
        t == typeof(byte)
        || t == typeof(sbyte)
        || t == typeof(short)
        || t == typeof(ushort)
        || t == typeof(int)
        || t == typeof(uint)
        || t == typeof(long)
        || t == typeof(ulong)
        || t == typeof(float)
        || t == typeof(double)
        || t == typeof(decimal);
}
